#ifndef _PHYSICS_EVENT_H_
#define _PHYSICS_EVENT_H_

#include <cstdint>
#include <vector>
#include "EventHits.h"

/**
 * @class PhysicsEvent
 * @brief Container for physics event generated by factory
 * 
 * Contains event number and associated detector hits for a single physics event.
 * A single PhysicsEvent can hold hits from multiple detector subsystems
 * (e.g. FADC waveforms, FADC scalers, TI scalers, VFTDC, MPD) which are
 * collected from different bank parsers and merged by event number.
 */
class PhysicsEvent {
    
private:
    int event_num;
    uint64_t event_timestamp;
    std::vector<std::shared_ptr<EventHits>> hits_list;
    
public:
    /**
     * @brief Default constructor
     * Initializes event number to -1
     */
    PhysicsEvent()
        : event_num(-1),
          event_timestamp(0) {}

    /**
     * @brief Constructor with a single EventHits
     * @param event_num Event number
     * @param hits Shared pointer to EventHits containing detector data
     */
    PhysicsEvent(int event_num, std::shared_ptr<EventHits> hits)
        : event_num(event_num),
          event_timestamp(0) {
        hits_list.push_back(std::move(hits));
    }

    int GetEventNumber() const {
        return event_num;
    }

    int SetEventNumber(int event_num) {
        this->event_num = event_num;
        return this->event_num;
    }

    uint64_t GetEventTimestamp() const {
        return event_timestamp;
    }

    uint64_t SetEventTimestamp(uint64_t event_timestamp) {
        this->event_timestamp = event_timestamp;
        return this->event_timestamp;
    }

    /**
     * @brief Add hits from another detector subsystem to this event
     * @param hits Shared pointer to EventHits to add
     */
    void addHits(std::shared_ptr<EventHits> hits) {
        hits_list.push_back(std::move(hits));
    }

    /**
     * @brief Move all hits from this event into another PhysicsEvent
     * 
     * Used during consolidation to merge PhysicsEvents that share
     * the same event number but were created by different parsers.
     * 
     * @param other The target PhysicsEvent to receive the hits
     */
    void insertHitsInto(PhysicsEvent& other) {
        if (other.GetEventTimestamp() == 0) {
            other.SetEventTimestamp(event_timestamp);
        }
        for (auto& hits : hits_list) {
            other.addHits(std::move(hits));
        }
        hits_list.clear();
    }

    /**
     * @brief Insert all detector hits into a JEvent
     * 
     * Iterates over all EventHits objects (from different subsystems)
     * and inserts each into the JEvent.
     */
    void insertHitsIntoEvent(JEvent& event) const {
        for (const auto& hits : hits_list) {
            hits->insertIntoEvent(event);
        }
    }
};

#endif // _PHYSICS_EVENT_H_
